### ISSUE TITLE
Google Api Quota

### ISSUE THREAD

**Issue by benox3** [orrybaram/Smelp#4]
Don't know if you guys are supporting this. (I thought it was a great idea).
It looks like you are reaching your limit on google api.

Over Quota

This application is temporarily over its serving quota. Please try again later.

**Comment by orrybaram** [comment]
Thanks for letting me know! I'll be pushing up a few changes that will hopefully help out with the server balancing.

**Comment by benox3** [comment]
No problem. I have some ideas if you want to open source the server api that I would love to contribute!

**Comment by orrybaram** [comment]
I opened it up, go for it!
https://github.com/orrybaram/netflixRottenizerServer
